# Generated by Django 4.0.3 on 2022-05-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
