# Generated by Django 4.0.3 on 2022-06-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default=2, upload_to='images'),
            preserve_default=False,
        ),
    ]
